# N皇后问题
在一个国际象棋棋盘上，摆放皇后棋子，使得每一行、列、对角线仅有一个皇后。  
目标是使得旗子数量最多。

In [25]:
#!/usr/bin/env python3.7

# Copyright 2020, Gurobi Optimization, LLC

# This example uses the Python matrix API to formulate the n-queens
# problem; it maximizes the number queens placed on an n x n
# chessboard without threatening each other.
#
# This example demonstrates NumPy slicing.

import numpy as np
import scipy.sparse as sp
import gurobipy as gp
from gurobipy import GRB

In [26]:
# Size of the n x n chess board
n = 8

In [27]:
# Create a new model
m = gp.Model("matrix2")

In [28]:
# Create a 2-D array of binary variables
# x[i,j]=1 means that a queen is placed at square (i,j)
x = m.addMVar((n, n), vtype=GRB.BINARY, name='x')

In [29]:
x

<(8, 8) matrix variable>

In [30]:
# Set objective - maximize number of queens
m.setObjective(x.sum(), GRB.MAXIMIZE)

In [41]:
# Add row and column constraints
for i in range(n):
    
    # At most one queen per row
    m.addConstr(x[i, :].sum() <= 1, name='row'+str(i))
    
    # At most one queen per column
    m.addConstr(x[:, i].sum() <= 1, name='col'+str(i))

### Core part: 对角线不冲突

In [32]:
# Add diagonal constraints
for i in range(1, 2*n):
    
    # At most one queen per diagonal
    diagn = (range(max(0, i-n), min(n, i)), range(min(n, i)-1, max(0, i-n)-1, -1))
    m.addConstr(x[diagn].sum() <= 1, name='diag'+str(i))
    # print(diagn)

    # At most one queen per anti-diagonal
    adiagn = (range(max(0, i-n), min(n, i)), range(max(0, n-i), min(n, 2*n-i)))
    m.addConstr(x[adiagn].sum() <= 1, name='adiagn'+str(i))
    # print(adiagn)

In [33]:
m.optimize()

Gurobi Optimizer version 9.0.0 build v9.0.0rc2 (mac64)
Optimize a model with 158 rows, 64 columns and 256 nonzeros
Model fingerprint: 0x523080b3
Variable types: 0 continuous, 64 integer (64 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 12.0000000
Presolve removed 146 rows and 40 columns
Presolve time: 0.00s
Presolved: 12 rows, 24 columns, 48 nonzeros
Found heuristic solution: objective 13.0000000
Variable types: 0 continuous, 24 integer (24 binary)

Root relaxation: objective 1.400000e+01, 7 iterations, 0.00 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

*    0     0               0      14.0000000   14.00000  0.00%     -    0s

Explored 0 nodes (7 simplex iterations) in 0.12 seconds
Thread count was 4 (of 4 available p

In [45]:
print(x.X)
print('Queens placed: %g' % m.objVal)

[[-0. -0. -0. -0.  1. -0.  0. -0.]
 [-0.  1. -0. -0. -0.  0. -0. -0.]
 [-0. -0. -0. -0.  0.  1. -0.  0.]
 [ 1. -0. -0. -0.  0. -0. -0. -0.]
 [ 0. -0.  0. -0. -0. -0.  1.  0.]
 [-0. -0. -0.  1. -0. -0.  0. -0.]
 [-0.  0.  0. -0. -0.  0. -0.  1.]
 [-0. -0.  1.  0. -0. -0. -0. -0.]]
Queens placed: 8
